version: '3'

services:
  api.todayintel.com:
    build: .
    image: izdrail/intel.izdrail.com:latest
    container_name: api.todayintel.com
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - type: bind
        source: .
        target: /app/
